### PR TITLE
Fix the iOS 17 UIKit issue that UIImageView entering the background will reset CALayer's contents, which cause SDAnimatedImageView render issue (out-of-sync)

### LINKED ISSUE #3635: iOS17.0.1 go background and go foreground, SDAnimatedImageView not display the image.
## demo code

```
    NSString *imgName = @"test@3x";
    NSString *imgType = @"webp";
    NSString *path = [[NSBundle mainBundle] pathForResource:imgName ofType:imgType];
    NSURL *imgUrl = [NSURL fileURLWithPath:path];

    [self.imageView sd_setImageWithURL:imgUrl
                      placeholderImage:nil
                               options:SDWebImageProgressiveLoad | SDWebImageScaleDownLargeImages
                               context:@{SDWebImageContextImageForceDecodePolicy: @(SDImageForceDecodePolicyNever)}
    ];
    self.imageView.shouldCustomLoopCount = YES;
    self.imageView.animationRepeatCount = 1;
```

**Github does not allow uploading webp images**

## procedure

first webp image display normally.
Screenshot 2023-11-13 at 5 17 52 PM

when app go background and go foreground, imageView not display the image correctly。
Screenshot 2023-11-13 at 5 18 16 PM

### PR DESCRIPTION
**Pull request by dreampiggy**
### New Pull Request Checklist

* [ ] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [ ] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [ ] I have searched for a similar pull request in the [project](https://github.com/rs/SDWebImage/pulls) and found none

* [ ] I have updated this branch with the latest master to avoid conflicts (via merge from master or rebase)
* [ ] I have added the required tests to prove the fix/feature I am adding
* [ ] I have updated the documentation (if necessary)
* [ ] I have run the tests and they pass
* [ ] I have run the lint and it passes (`pod lib lint`)

This merge request fixes / refers to the following issues: ...

### Pull Request Description

See more information in #3635 and details debugging steps

This close #3635

### Solution

Should use traitCollectionDidChange to refresh the CALayer's contents status to match current frame index

### CODE REVIEW

File: SDWebImage/Core/SDAnimatedImageView.m [hunk 1]
```diff
@@ -501,6 +501,17 @@ - (void)displayLayer:(CALayer *)layer
...
 }
 
+#if SD_UIKIT
+- (void)traitCollectionDidChange:(UITraitCollection *)previousTraitCollection {
+    // See: #3635
+    // From iOS 17, when UIImageView entering the background, it will receive the trait collection changes, and modify the CALayer.contents by `self.image.CGImage`
+    // However, For animated image, `self.image.CGImge != self.currentFrame.CGImage`, right ?
+    // So this cause the render issue, we need to reset the CALayer.contents again
+    [super traitCollectionDidChange:previousTraitCollection];
+    [self.imageViewLayer setNeedsDisplay];
```
Comment (dreampiggy) [inline SDWebImage/Core/SDAnimatedImageView.m:511]: @longjianjiang Should we guard an `@available (iOS 17.0, *)` version check here ?

From

**Comment by dreampiggy** [comment]
@longjianjiang Does this fix the issue ?

**Comment by longjianjiang** [comment]
> @longjianjiang Does this fix the issue ?

yes.
