### PR TITLE
Fix the bug when the thumbnail pixel size is larger than the pixel size, and the image has EXIF orientation, the final UIImage will use wrong image orientation

### LINKED ISSUE #3062: iPad上拍摄的图片加载时出现错误的旋转
### New Issue Checklist

* [ √] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [ √] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [ √] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | 13.5
 SDWebImage Version      | 5.8.0
 Integration Method      | cocoapods
 Xcode Version           | Xcode 11 
 Repro rate              | all the time (100%)
 Repro with our demo prj | 
 Demo project link       | 

### Issue Description and Steps

使用场景是这样的：
1. 使用iPad在竖屏时拍摄一张图片，并上传到服务器
2. 使用 UIImageView+WebCache 中的 方法
` - (void)sd_setImageWithURL:(nullable NSURL *)url placeholderImage:(nullable UIImage *)placeholder options:(SDWebImageOptions)options completed:(nullable SDExternalCompletionBlock)completedBlock;`
去加载已经上传到服务器中的图片，其中 options 设置为  SDWebImageScaleDownLargeImages

现象：图片内容出现了不正确的向左旋转90°

可以确认：
1. 上传到服务器的图片是正常的，使用浏览器打开这张图片时显示是正常的
2. 在 SDImageIOAnimatedCoder 中的 
`+ (UIImage *)createFrameAtIndex:(NSUInteger)index source:(CGImageSourceRef)source scale:(CGFloat)scale preserveAspectRatio:(BOOL)preserveAspectRatio thumbnailSize:(CGSize)thumbnailSize options:(NSDictionary *)options;`
在该方法中可以看到，原本的图片信息中，`exifOrientation = kCGImagePropertyOrientationRight`
但是，被该方法下面的逻辑
```
if (thumbnailSize.width > 0 && thumbnailSize.height > 0) {
        if (preserveAspectRatio) {
            // kCGImageSourceCreateThumbnailWithTransform will apply EXIF transform as well, we should not apply twice
            exifOrientation = kCGImagePropertyOrientationUp;
        } else {
            // `CGImageSourceCreateThumbnailAtIndex` take only pixel dimension, if not `preserveAspectRatio`, we should manual scale to the target size
            CGImageRef scaledImageRef = [SDImageCoderHelper CGImageCreateScaled:imageRef size:thumbnailSize];
            CGImageRelease(imageRef);
            imageRef = scaledImageRef;
        }
    }
```
强制修改为 kCGImagePropertyOrientationUp
3. 将上面逻辑中的 `exifOrientation = kCGImagePropertyOrientationUp;`注释掉后，重新下载的图片恢复正常显示

### PR DESCRIPTION
**Pull request by dreampiggy**
### New Pull Request Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar pull request in the [project](https://github.com/rs/SDWebImage/pulls) and found none

* [x] I have updated this branch with the latest master to avoid conflicts (via merge from master or rebase)
* [x] I have added the required tests to prove the fix/feature I am adding
* [x] I have updated the documentation (if necessary)
* [x] I have run the tests and they pass
* [x] I have run the lint and it passes (`pod lib lint`)

This merge request fixes / refers to the following issues: fix #3062 

### Pull Request Description

This mistake take from ~~5.5.0 to 5.8.4~~ Eidt, from 5.8.2 to 5.8.4. Maybe need another patch version for 5.8 ? Or just release 5.9

### CODE REVIEW

File: SDWebImage/Core/SDImageIOAnimatedCoder.m [hunk 1]
```diff
@@ -251,8 +252,8 @@ + (UIImage *)createFrameAtIndex:(NSUInteger)index source:(CGImageSourceRef)sourc
     if (!imageRef) {
         return nil;
     }
-    
-    if (thumbnailSize.width > 0 && thumbnailSize.height > 0) {
```
Comment (dreampiggy) [inline SDWebImage/Core/SDImageIOAnimatedCoder.m:255]: This seems not update with the new changes from #3039
