### PR TITLE
Fix the race condition when user cancel the network loading will not trigger the completion block

### LINKED ISSUE #3141: Completion isn't called when cancel performed async for the second app launch
### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | 14.3
 SDWebImage Version      | 5.9.4
 Integration Method      | cocoapods
 Xcode Version           | Xcode 12.3
 Repro rate              | all the time (100%)
 Repro with our demo prj | -
 Demo project link       | https://github.com/anton-plebanovich/SingleView/tree/52a19067cc0680587167b448e3682cc5a854a450

### Issue Description and Steps

Code:
```swift
        // Works well on the FIRST app launch only.
        // Clearing cache doesn't help.
        SDImageCache.shared.clear(with: .all) { [self] in
            
            print("set image")
            imageView.sd_setImage(with: url) { _, _, _, _ in
                print("completion")
            }
            
            DispatchQueue.main.async { [self] in
                print("cancel")
                imageView.sd_cancelCurrentImageLoad()
            }
        }
```

The first launch output:
```
set image
cancel
completion
```

The second launch output:
```
set image
cancel
```

Probably related to https://github.com/SDWebImage/SDWebImage/pull/2692/files
- Clone, install pods and run project https://github.com/anton-plebanovich/SingleView/tree/52a19067cc0680587167b448e3682cc5a854a450
- Launch app the first time -> completion called
- Launch app a second time -> completion isn't called

I can only guess it's related to not handled completion calls in `SDImageCachesManager`, e.g. line 291:
```swift
            if (operation.isCancelled) {
                // Cancelled
                return;
            }
```

### PR DESCRIPTION
**Pull request by dreampiggy**
### New Pull Request Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar pull request in the [project](https://github.com/rs/SDWebImage/pulls) and found none

* [x] I have updated this branch with the latest master to avoid conflicts (via merge from master or rebase)
* [x] I have added the required tests to prove the fix/feature I am adding
* [x] I have updated the documentation (if necessary)
* [ ] I have run the tests and they pass
* [ ] I have run the lint and it passes (`pod lib lint`)

This merge request fixes / refers to the following issues: #3141

### Pull Request Description

This close #3141 

Now we do not relay on URLSession delegate timing, directly callback when cancelled.

### CODE REVIEW

File: SDWebImage/Core/SDWebImageDownloaderOperation.m [hunk 1]
```diff
@@ -232,18 +232,23 @@ - (void)cancel {
...
-        });
-
-        // As we cancelled the task, its callback won't be called and thus won't
-        // maintain the isFinished and isExecuting flags.
-        if (self.isExecuting) self.executing = NO;
-        if (!self.isFinished) self.finished = YES;
+        self.dataTask = nil;
+        // Provide the same userInfo as URLSession if network is cancelled
+        // Don't relay on `URLSession:task:didCompleteWithError:` delegate callback because it may delay
+        [self callCompletionBlocksWithError:[NSError errorWithDomain:NSURLErrorDomain code:NSURLErrorCancelled userInfo:@{NSLocalizedDescriptionKey: @"cancelled", NSURLErrorFailingURLErrorKey: self.request.URL, NSURLErrorFailingURLStringErrorKey: self.request.URL.absoluteString}]];
```
Comment (dreampiggy) [inline SDWebImage/Core/SDWebImageDownloaderOperation.m:251]: Should we just return the same `SDWebImageErrorDomain.SDWebImageErrorCancelled` as other cancel timing cases ?

I don't knwo whether this change is suitable for most cases. @Insofan

Comment (dreampiggy) [reply SDWebImage/Core/SDWebImageDownloaderOperation.m]: I change this into the `SDWebImageErrorDomain.SDWebImageErrorCancelled`, which pass the unit test.
This design is the same as Kingfisher.
