### PR TITLE
Use the new solution for CADisplayLink duration calculation and fix 90Hz/120Hz display (iPhone Pro or Vision Pro)

### LINKED ISSUE #3579: SDAnimatedImageView播放apng动画时，在iPhone 13 pro机型上太快，应该是因为手机是120Hz刷新频率导致的，希望修复
### New Issue Checklist

* [ ] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [ ] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [ ] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | e.g. ios / macos / tvos / watchos
 Platform Version        | e.g. 12.0 / 10.14.0 / 12.0 / 5.0
 SDWebImage Version      | e.g. 5.0.0 / 4.4.0
 Integration Method      | e.g. carthage / cocoapods / manually
 Xcode Version           | e.g. Xcode 11 / Xcode 10
 Repro rate              | e.g. all the time (100%) / sometimes x% / only once
 Repro with our demo prj | e.g. does it happen with our demo project?
 Demo project link       | e.g. link to a demo project that highlights the issue

### Issue Description and Steps

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

### PR DESCRIPTION
**Pull request by dreampiggy**
### Pull Request Description

This visually fix visionOS (90Hz) animated image duration

We don't use Media Time because it's not correct when lag or VSync not callback in current runloop

Instead, we use the `next targetTimestamp - previous targetTimestamp` to get the actual time during callbacks

### Demo

Testing the Vision Simulator from Xcode 15.1, works better than current version (Current version will play large GIF in slow because the decoding of GIF is slow, and out-of-sync after 10 frames)

### Fix

This close #3579 as well

### CODE REVIEW

File: SDWebImage/Private/SDDisplayLink.m [hunk 1]
```diff
@@ -219,17 +241,17 @@ - (void)stop {
 }
 
 - (void)displayLinkDidRefresh:(id)displayLink {
+#pragma clang diagnostic push
+#pragma clang diagnostic ignored "-Warc-performSelector-leaks"
+    [_target performSelector:_selector withObject:self];
```
Comment (dreampiggy) [inline SDWebImage/Private/SDDisplayLink.m:246]: The first callback (in `SDAnimatedImagePlayer`) will get an temp status about `duration`, because at this time, the previous `targetTimestamp` or `timestamp` is not set. We have some fallback logic

Then the second callback the duration will be accurate enough
