### PR TITLE
Fixes crash for apng coder when properties are nil

### LINKED ISSUE #2689: 您好，更新到5.0.0 后有些手机崩溃
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | e.g. ios 
 Platform Version        | e.g. 12.0 
 SDWebImage Version      | e.g. 5.0.0 
 Integration Method      | e.g.  cocoapods 
 Xcode Version           | e.g. Xcode 10 
 Repro rate              | e.g.  sometimes x% /
 Repro with our demo prj | e.g. does it happen with our demo project?
 Demo project link       | e.g. link to a demo project that highlights the issue

### Issue Description and Steps
 0	CoreFoundation
CFRelease + 124
1	lianzhituan
-[SDImageAPNGCoder sd_frameDurationAtIndex:source:] (SDImageAPNGCoder.m:173)
2	lianzhituan
-[SDImageAPNGCoder scanAndCheckFramesValidWithImageSource:] (SDImageAPNGCoder.m:368)
3	lianzhituan
-[SDImageAPNGCoder updateIncrementalData:finished:] (SDImageAPNGCoder.m:291)
4	lianzhituan
SDImageLoaderDecodeProgressiveImageData (SDImageLoader.m:123)
5	lianzhituan
__68-[SDWebImageDownloaderOperation URLSession:dataTask:didReceiveData:]_block_invoke (SDWebImageDownloaderOperation.m:0)
6	libdispatch.dylib
__dispatch_call_block_and_release + 24
7	libdispatch.dylib
__dispatch_client_callout + 16
8	libdispatch.dylib
__dispatch_lane_serial_drain$VARIANT$armv81 + 548
9	libdispatch.dylib
__dispatch_lane_invoke$VARIANT$armv81 + 412
10	libdispatch.dylib
__dispatch_workloop_worker_thread + 584
11	libsystem_pthread.dylib
_pthread_wqthread + 312

image
捕获到的崩溃信息，请问这是什么问题？

### PR DESCRIPTION
**Pull request by zhongwuzw**
### New Pull Request Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar pull request in the [project](https://github.com/rs/SDWebImage/pulls) and found none

* [x] I have updated this branch with the latest master to avoid conflicts (via merge from master or rebase)
* [x] I have added the required tests to prove the fix/feature I am adding
* [x] I have updated the documentation (if necessary)
* [x] I have run the tests and they pass
* [x] I have run the lint and it passes (`pod lib lint`)

This merge request fixes / refers to the following issues: ...

### Pull Request Description

Fixes #2689 .

### CODE REVIEW

File: SDWebImage/SDImageAPNGCoder.m [hunk 1]
```diff
@@ -154,6 +154,9 @@ - (float)sd_frameDurationAtIndex:(NSUInteger)index source:(CGImageSourceRef)sour
     float frameDuration = 0.1f;
     CFDictionaryRef cfFrameProperties = CGImageSourceCopyPropertiesAtIndex(source, index, nil);
     NSDictionary *frameProperties = (__bridge NSDictionary *)cfFrameProperties;
```
Comment (dreampiggy) [inline SDWebImage/SDImageAPNGCoder.m]: Seems a bug. What about using the same code like GIF coder ? Just check before Toll-free bridging.

```objective-c
CFDictionaryRef cfFrameProperties = CGImageSourceCopyPropertiesAtIndex(source, index, nil);
if (!cfFrameProperties) {
    return frameDuration;
}
```

Comment (zhongwuzw) [reply SDWebImage/SDImageAPNGCoder.m]: Umm, yeah, it's trivial but I can update to prevent pointer static cast.
