### PR TITLE
Quick fix the issue that UIImage.sd_decodeOptions cause retain cycle when pass custom cache in context option

### LINKED ISSUE #3371: SDMemoryCache  dealloc崩溃
image

image

### PR DESCRIPTION
**Pull request by dreampiggy**
### New Pull Request Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar pull request in the [project](https://github.com/rs/SDWebImage/pulls) and found none

* [x] I have updated this branch with the latest master to avoid conflicts (via merge from master or rebase)
* [x] I have added the required tests to prove the fix/feature I am adding
* [x] I have updated the documentation (if necessary)
* [x] I have run the tests and they pass
* [x] I have run the lint and it passes (`pod lib lint`)

This merge request fix #3371

### Background

SDWebImage 5.13.2 introduce new `UIImage.sd_decodeOptions`, which retain the `SDWebImageContext`. However, it's dangerous. Because once you store a `SDImageCache` inside context options, this will cause retain cycle:

+ UIImage -> SDWebImageContextOptions -> SDImageCache -> SDMemoryCache(NSCache) -> UIImage

### Solution
Now the SDImageCoderWebImageContext does not pass the built-in options, only custom options will be passed, and deprecated in 5.14.0

### CODE REVIEW

File: SDWebImage/Core/SDImageCacheDefine.m [hunk 1]
```diff
@@ -13,6 +13,37 @@
 #import "UIImage+Metadata.h"
 #import "SDInternalMacros.h"
 
+static NSArray<NSString *>* GetKnownContextOptions(void) {
```
Comment (dreampiggy) [inline SDWebImage/Core/SDImageCacheDefine.m:16]: Hack for 5.13. In 5.14 I will remove this and use new `SDWebImageContextImageDecodeOptions` instead.

See more in PR
