### PR TITLE
Fix the missing lock for callbackTokens which may cause thread-safe issue

### LINKED ISSUE #3433: Crash SDWebImageDownloaderOperation.m line 247
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | 16.0
 SDWebImage Version      | 5.14.0
 Integration Method      | spm
 Xcode Version           | Xcode 
 Repro rate              | sometimes (2%)
 Repro with our demo prj | not tested
 Demo project link       | n/a

### Issue Description and Steps

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

I'm seeing lots of crashes on Firebase since updating to `v 5.14.0`

Screenshot 2022-11-09 at 15 44 17

### LINKED ISSUE #3437: 最新版SDK5.14.0报错 [SDWebImageDownloaderOperation start]
*** -[NSArray initWithArray:range:copyItems:]: range {0, 1} extends beyond bounds for empty array

### LINKED ISSUE #3438: 最新版SDK5.14.0报错[SDWebImageDownloaderOperation start]
-[NSArray initWithArray:range:copyItems:]: range {0, 1} extends beyond bounds for empty array

CoreFoundation
___exceptionPreprocess + 220

3
CoreFoundation
-[NSArray initWithArray:range:copyItems:] + 680
4
SDWebImage
-[SDWebImageDownloaderOperation start] + 1648
5
Foundation
___NSOPERATIONQUEUE_IS_STARTING_AN_OPERATION__ + 24

14
libsystem_pthread.dylib
_start_wqthread + 8
image

### PR DESCRIPTION
**Pull request by dreampiggy**
### New Pull Request Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar pull request in the [project](https://github.com/rs/SDWebImage/pulls) and found none

* [x] I have updated this branch with the latest master to avoid conflicts (via merge from master or rebase)
* [x] I have added the required tests to prove the fix/feature I am adding
* [x] I have updated the documentation (if necessary)
* [x] I have run the tests and they pass
* [x] I have run the lint and it passes (`pod lib lint`)

This merge request fixes / refers to the following issues: ...

### Pull Request Description

This fix #3438 fix #3437 fix #3433 (see comments)

#### Reason

That `token` is not locked by the synchonized, so it's not thread safe.

#### Changes

Move block before sending to the main queue

This can avoid some life cycle issue and increase performance

### CODE REVIEW

File: SDWebImage/Core/SDWebImageDownloaderOperation.m [hunk 1]
```diff
@@ -244,7 +244,10 @@ - (void)start {
             self.coderQueue.qualityOfService = NSQualityOfServiceDefault;
         }
         [self.dataTask resume];
-        NSArray<SDWebImageDownloaderOperationToken *> *tokens = [self.callbackTokens copy];
+        NSArray<SDWebImageDownloaderOperationToken *> *tokens;
+        @synchronized (self) {
+            tokens = [self.callbackTokens copy];
+        }
```
Comment (dreampiggy) [inline SDWebImage/Core/SDWebImageDownloaderOperation.m:250]: The thread safe issue is here. It's not guarded by `@synchronized`
