### PR TITLE
Fix some regression when SDAnimatedImage created with static format like JPEG

### LINKED ISSUE #3706: 5.18.4+ SDAnimatedImage static image support performance issue
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | 15.0 +
 SDWebImage Version      | 5.18.4 +
 Integration Method      | SPM
 Xcode Version           | Xcode 15
 Repro rate              | all the time (100%)
 Repro with our demo prj | -
 Demo project link       | sorry unable to provide

### Issue Description and Steps

Hi, I have particularly strange issue encountered which I narrowed down to this particular change of SDAnimatedImage:

[5.18.4 - 5.18 Fix, on Oct 27th, 2023](https://github.com/rs/SDWebImage/releases/tag/5.18.4)
SDAnimatedImage now supports static image like JPEG data #3626 #3625
Previous version the initializer will return nil and has to use UIImage/NSImage instead

When downloading images from the web, we sometimes don't know for sure beforehand if this image is animated or not. Although we can guess from the url extension, we'd prefer the process to be more automatic. So in some occasions, we would pass 
`context[.animatedImageClass] = SDAnimatedImage.self`
to ask SDWebImage to try use animated image if possible. In previous versions, if this image is not an animated image, it would fallback to a regular UIImage, which we have no issue with. 

After upgrading to the 5.18.4+ however, the newly added mechanism would create a SDAnimatedImage instead of returning nil, this seems to bring noticeable performance overhead when scrolling in a UICollectionView. We use a subclass of SDAnimatedImageView as a general purpose image view that can show either regular or animated images. Scrolling in this case becomes quite choppy, I tried to look into the source code but was unable to understand the full picture. And sorry I do not have any reliable way to benchmark this except from purely observations. I tried 5.18.3 or try not pass `context[.animatedImageClass] = SDAnimatedImage.self`, the scrolling becomes very smooth again. 

I am wondering if it is possible to add an additional SDImageCoderOptions to configure this behavior? Namely, could we add an option so that SDAnimatedImage would fail to create like in the past and we would fallback to a simple UIImage?

### PR DESCRIPTION
**Pull request by dreampiggy**
### New Pull Request Checklist

* [ ] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [ ] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [ ] I have searched for a similar pull request in the [project](https://github.com/rs/SDWebImage/pulls) and found none

* [ ] I have updated this branch with the latest master to avoid conflicts (via merge from master or rebase)
* [ ] I have added the required tests to prove the fix/feature I am adding
* [ ] I have updated the documentation (if necessary)
* [ ] I have run the tests and they pass
* [ ] I have run the lint and it passes (`pod lib lint`)

This merge request fixes / refers to the following issues: close #3706 

### Pull Request Description

For now, I still prefer to keep the idea that `SDAnimatedImage` can be created with non-static format like JPEG.

Why ?  Because even without the changes in #3626, you can still do hack using `NSCoder` to create a JPEG `SDAnimatedImage` object, before 5.19.0 version...😂 (See the line of code)

image

And this, match the behavior like `subclassing` (For the same input param, the parent class `UIImage` can init successfully, but why a subclass return nil ?)

And this matches the YYImage's behavior, it's more easy to keep sync of that https://github.com/SDWebImage/SDWebImageYYPlugin

CC @LeoTheCatMeow

### CODE REVIEW

File: SDWebImage/Core/SDAnimatedImage.m [hunk 1]
```diff
@@ -335,7 +335,7 @@ - (NSUInteger)sd_memoryCost {
 @implementation SDAnimatedImage (Metadata)
 
 - (BOOL)sd_isAnimated {
-    return YES;
+    return self.animatedImageFrameCount > 1;
```
Comment (dreampiggy) [inline SDWebImage/Core/SDAnimatedImage.m:338]: That https://github.com/SDWebImage/SDWebImageYYPlugin need to update with this behavior as we..

File: SDWebImage/Core/SDAnimatedImageView.m [hunk 2]
```diff
@@ -129,12 +129,12 @@ - (void)setImage:(UIImage *)image
     
     // We need call super method to keep function. This will impliedly call `setNeedsDisplay`. But we have no way to avoid this when using animated image. So we call `setNeedsDisplay` again at the end.
     super.image = image;
-    if ([image.class conformsToProtocol:@protocol(SDAnimatedImage)]) {
+    if ([image.class conformsToProtocol:@protocol(SDAnimatedImage)] && [(id<SDAnimatedImage>)image animatedImageFrameCount] > 1) {
```
Comment (dreampiggy) [inline SDWebImage/Core/SDAnimatedImageView.m:132]: For some case, like a single frame `GIF` in `SDAnimatedImage`, this will cause behavior changes. But I think still worth.

Single frame animated image format (1 frame GIF) actually can always consider as `Static image`, right ?

File: SDWebImage/Core/SDWebImageDefine.m [hunk 3]
```diff
@@ -83,9 +83,10 @@ inline CGFloat SDImageScaleFactorForKey(NSString * _Nullable key) {
                 scaledImage = [[image.class alloc] initWithData:data scale:scale];
             }
         }
-        if (scaledImage) {
-            return scaledImage;
-        }
+    }
+    if (scaledImage) {
+        SDImageCopyAssociatedObject(image, scaledImage);
```
Comment (dreampiggy) [inline SDWebImage/Core/SDWebImageDefine.m:88]: A bug during my review of this API

File: SDWebImage/Core/SDAnimatedImage.m [hunk 4]
```diff
@@ -347,11 +347,21 @@ - (void)setSd_imageLoopCount:(NSUInteger)sd_imageLoopCount {
 }
 
 - (NSUInteger)sd_imageFrameCount {
-    return self.animatedImageFrameCount;
+    NSUInteger frameCount = self.animatedImageFrameCount;
```
Comment (dreampiggy) [inline SDWebImage/Core/SDAnimatedImage.m:350]: For non animated `SDAnimatedImage`, `self.animatedImageFrameCount` is nil, so the extra check is need.

**Comment by dreampiggy** [comment]
This class will rename into `SDImage` in the future

**Comment by LeoTheCatMeow** [comment]
Verified that the scroll performance issue has been resolved. Looks good!
